/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fund2;

import org.eclipse.jetty.server.Server;

import io.github.cdimascio.dotenv.Dotenv;

/**
 * Main class that creates and start the Continuous Integration server
 */

public class App {

    public static Dotenv dotenv = Dotenv.load();

    // used to start the CI server in command line
    public static void main(String[] args) throws Exception {
        int port = Integer.parseInt(dotenv.get("PORT"));
        Server server = new Server(port);
        server.setHandler(new ContinuousIntegrationServer());
        server.start();
        server.join();
    }
}
